package main

// Internal service authentication (per-installation token).
//
// One random token, generated by `atlas init` into
// secrets/service-token (0600) and mounted read-only into every
// container at /run/atlas-secrets/service-token, authenticates
// internal and client requests as `Authorization: Bearer <token>`.
//
// Enforcement is enabled iff a token file is configured and readable —
// an install that never ran `atlas init` keeps today's open-localhost
// behavior, and `atlas doctor` flags it. /health and /ready stay
// unauthenticated (compose/K8s probes are headerless curl).
//
// The token value must never be logged, placed in argv, or echoed in
// error bodies.

import (
	"crypto/subtle"
	"log"
	"net/http"
	"os"
	"strings"
)

// serviceToken is loaded once at startup. Rotation = rewrite the file
// (atlas init --rotate-token) + restart the stack.
var serviceToken = loadServiceToken()

func loadServiceToken() string {
	path := os.Getenv("ATLAS_SERVICE_TOKEN_FILE")
	if path == "" {
		path = "/run/atlas-secrets/service-token"
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "" // unconfigured => auth disabled (doctor warns)
	}
	return strings.TrimSpace(string(data))
}

// authOpenPaths never require the token: health probes are headerless
// curl in compose/K8s, and /ready gates orchestration.
func authOpenPath(path string) bool {
	return path == "/health" || path == "/ready"
}

func bearerToken(r *http.Request) string {
	h := r.Header.Get("Authorization")
	const prefix = "Bearer "
	if strings.HasPrefix(h, prefix) {
		return h[len(prefix):]
	}
	return ""
}

// requireServiceToken wraps a handler with token enforcement.
func requireServiceToken(next http.Handler) http.Handler {
	if serviceToken == "" {
		return next
	}
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if authOpenPath(r.URL.Path) {
			next.ServeHTTP(w, r)
			return
		}
		got := bearerToken(r)
		if subtle.ConstantTimeCompare([]byte(got), []byte(serviceToken)) != 1 {
			// No token material in the response or the log line.
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusUnauthorized)
			_, _ = w.Write([]byte(`{"error":"unauthorized","detail":"internal service auth is enabled; send Authorization: Bearer <service-token> (secrets/service-token)"}`))
			return
		}
		next.ServeHTTP(w, r)
	})
}

// tokenTransport injects the service token into outbound requests
// (proxy -> llama/v3/lens/sandbox) unless the caller already set an
// Authorization header (e.g. the /v1/chat passthrough forwarding a
// client's own header).
type tokenTransport struct {
	base http.RoundTripper
}

func (t *tokenTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	if serviceToken != "" && req.Header.Get("Authorization") == "" {
		req = req.Clone(req.Context())
		req.Header.Set("Authorization", "Bearer "+serviceToken)
	}
	base := t.base
	if base == nil {
		base = http.DefaultTransport
	}
	return base.RoundTrip(req)
}

// installTokenTransport wires outbound injection through the two
// transport choke points: the process default (covers every client
// with a nil Transport — http.DefaultClient, &http.Client{} literals,
// http.Post) and the dedicated LLM streaming client.
func installTokenTransport() {
	if serviceToken == "" {
		return
	}
	http.DefaultTransport = &tokenTransport{base: http.DefaultTransport}
	llmStreamClient.Transport = &tokenTransport{base: llmStreamClient.Transport}
	log.Printf("  Internal auth: enabled (token file configured)")
}
