"""A self-test suite that passes nothing cannot condemn a candidate.

The cases are generated by the same model that writes the candidates, and
for these tasks producing an expected output IS solving the problem. So a
wrong answer key and wrong code are indistinguishable at a score of zero.

Measured across a 28-session run: 0 of 44 candidates passed the sandbox,
with scores of 0/5, 0/4, 0/3 and never a partial. The check rejected every
candidate it saw, which is not evidence — and it cost the pipeline every
winner it might have had, since every passing session in every run was won
by the model's own direct write rather than by a V3 candidate.

A partial score is different in kind: the suite has demonstrated some case
is passable, so falling below half is the candidate underperforming a bar
something else cleared.
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "v3-service"))

import pipeline  # noqa: E402


def _verdict(passed: int, total: int):
    """The decision the pipeline makes from a self-test score.

    Mirrors the branch under test: zero is inconclusive and returns no
    verified candidate, a partial score below half fails the candidate, at
    or above half passes.
    """
    if total > 0 and passed == 0:
        return "inconclusive"
    if total > 0 and passed < total / 2:
        return "fail"
    return "pass"


def _returns_a_candidate(verdict: str) -> bool:
    """Only a pass puts a candidate in the pool the caller can receive."""
    return verdict == "pass"


def test_zero_of_n_no_longer_condemns_the_candidate():
    """The measured shape: every candidate scoring 0/5 against a suite the
    model wrote for a problem it could not solve."""
    assert _verdict(0, 5) == "inconclusive"
    assert _verdict(0, 4) == "inconclusive"
    assert _verdict(0, 3) == "inconclusive"


def test_inconclusive_does_not_certify_either():
    """Cannot condemn and therefore promote are different claims.

    Falling through to the build check made "it compiles" the whole of
    verification, so a candidate that failed every one of its own cases was
    marked passed and could be written over the model's work. Measured on
    the two tasks whose answer is computed from a file the program reads:
    0 of 4 sessions correct on the run that shipped it, against 1-2 of 4 on
    each of the four runs before.
    """
    assert not _returns_a_candidate(_verdict(0, 5))
    assert not _returns_a_candidate(_verdict(0, 3))
    # And a real pass still is one.
    assert _returns_a_candidate(_verdict(3, 5))


def test_a_partial_score_still_fails_a_weak_candidate():
    """Some case passed, so the suite is demonstrably passable and a
    candidate below half is genuinely underperforming."""
    assert _verdict(1, 5) == "fail"
    assert _verdict(2, 5) == "fail"


def test_a_majority_still_passes():
    assert _verdict(3, 5) == "pass"
    assert _verdict(5, 5) == "pass"
    assert _verdict(2, 4) == "pass"


def test_no_cases_at_all_is_not_a_failure():
    """A suite that could not be generated must not fail the candidate."""
    assert _verdict(0, 0) == "pass"


def test_the_inconclusive_stage_is_registered():
    """An unregistered stage contributes no phase row, so the run summary
    loses the reason verification declined to decide."""
    assert pipeline._STAGE_PHASE["self_test_inconclusive"] == "self_test"
